name: publish-tagy-site

on:
  push:
    branches:
    - master

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: pip install tagy==0.1.6
      - run: python build.py
