name: publish-tagy-site

on:
  push:
    branches:
    - master

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: build site
        run: pip install tagy==0.1.6
      - run: ./tagy.py -b
      
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "generated"
          git push -u origin gh-pages

