name: publish-tagy-site

on:
  push:
    branches:
    - master

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      
      
      #- name: config git
      #  run: |
      #    #git checkout --orphan gh-pages
      #    #git worktree add docs gh-pages

      - name: build site
        run: pip install tagy==0.1.6
      - run: ./tagy.py -b

      - run: |
          cd docs
          git init
          #git remote add origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git branch gh-pages
      - run: |
          git push -f "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"gh-pages
        

